##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## MakeFile Arcade-graph
##

all:
	$(MAKE) -C qix
	$(MAKE) -C snake
	$(MAKE) -C pacman
	$(MAKE) -C centipede

clean:
	$(MAKE) -C qix clean
	$(MAKE) -C snake clean
	$(MAKE) -C pacman clean
	$(MAKE) -C centipede clean

fclean:
	$(MAKE) -C qix fclean
	$(MAKE) -C snake fclean
	$(MAKE) -C pacman fclean
	$(MAKE) -C centipede fclean

debug:
	$(MAKE) -C qix debug
	$(MAKE) -C snake debug
	$(MAKE) -C pacman debug
	$(MAKE) -C centipede debug

