##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## MakeFile Arcade-graph
##

all:
	$(MAKE) -C ncurses
	$(MAKE) -C sdl2
	$(MAKE) -C sfml
	$(MAKE) -C xlib
	$(MAKE) -C allegro5
	$(MAKE) -C irrlicht

clean:
	$(MAKE) -C ncurses clean
	$(MAKE) -C sdl2 clean
	$(MAKE) -C sfml clean
	$(MAKE) -C xlib clean
	$(MAKE) -C allegro5 clean
	$(MAKE) -C irrlicht clean

fclean:
	$(MAKE) -C ncurses fclean
	$(MAKE) -C sdl2 fclean
	$(MAKE) -C sfml fclean
	$(MAKE) -C xlib fclean
	$(MAKE) -C allegro5 fclean
	$(MAKE) -C irrlicht fclean

debug:
	$(MAKE) -C ncurses debug
	$(MAKE) -C sdl2 debug
	$(MAKE) -C sfml debug
	$(MAKE) -C xlib debug
	$(MAKE) -C allegro5 debug
	$(MAKE) -C irrlicht debug

